-- Add company details fields for requisites and contact info
ALTER TABLE companies 
  ADD COLUMN IF NOT EXISTS inn VARCHAR(12),
  ADD COLUMN IF NOT EXISTS kpp VARCHAR(9),
  ADD COLUMN IF NOT EXISTS ogrn VARCHAR(15),
  ADD COLUMN IF NOT EXISTS legal_address TEXT,
  ADD COLUMN IF NOT EXISTS actual_address TEXT,
  ADD COLUMN IF NOT EXISTS bank_name VARCHAR(255),
  ADD COLUMN IF NOT EXISTS bik VARCHAR(9),
  ADD COLUMN IF NOT EXISTS correspondent_account VARCHAR(20),
  ADD COLUMN IF NOT EXISTS account_number VARCHAR(20),
  ADD COLUMN IF NOT EXISTS contact_person VARCHAR(255),
  ADD COLUMN IF NOT EXISTS phone VARCHAR(20),
  ADD COLUMN IF NOT EXISTS email VARCHAR(255);
